// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listInboxFeed = `-- name: ListInboxFeed :many
SELECT
    'event'::text          AS entry_type,
    ie.kind,
    ie.source_user_id,
    u.username             AS source_username,
    ie.room_id             AS ref_room_id,
    NULL::bigint           AS ref_conversation_id,
    0::bigint              AS unread_count,
    NULL::text             AS last_message_body,
    NULL::bigint           AS last_message_sender_id,
    r.name                 AS room_name,
    0::bigint              AS peer_id,
    ''::text               AS peer_username,
    ie.created_at
FROM inbox_events ie
JOIN users u ON u.id = ie.source_user_id
LEFT JOIN rooms r ON r.id = ie.room_id
WHERE ie.user_id = $2
UNION ALL
SELECT
    'conversation'::text   AS entry_type,
    ''::text               AS kind,
    0::bigint              AS source_user_id,
    ''::text               AS source_username,
    ic.ref_room_id,
    ic.ref_conversation_id,
    ic.unread_count::bigint,
    ic.last_message_body,
    ic.last_message_sender_id,
    r.name                 AS room_name,
    COALESCE(peer.id, 0)   AS peer_id,
    COALESCE(peer.username, '') AS peer_username,
    ic.last_message_at     AS created_at
FROM inbox_conversations ic
LEFT JOIN rooms r ON r.id = ic.ref_room_id
LEFT JOIN conversations c ON c.id = ic.ref_conversation_id
LEFT JOIN users peer ON peer.id = CASE WHEN c.user_a = $2::bigint THEN c.user_b ELSE c.user_a END
WHERE ic.user_id = $2
  AND ic.last_message_at IS NOT NULL
ORDER BY created_at DESC
LIMIT $1
`

type ListInboxFeedParams struct {
	Lim    int32
	UserID int64
}

type ListInboxFeedRow struct {
	EntryType           string
	Kind                string
	SourceUserID        int64
	SourceUsername      string
	RefRoomID           pgtype.Int8
	RefConversationID   pgtype.Int8
	UnreadCount         int64
	LastMessageBody     pgtype.Text
	LastMessageSenderID pgtype.Int8
	RoomName            pgtype.Text
	PeerID              int64
	PeerUsername        string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) ListInboxFeed(ctx context.Context, arg ListInboxFeedParams) ([]ListInboxFeedRow, error) {
	rows, err := q.db.Query(ctx, listInboxFeed, arg.Lim, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxFeedRow
	for rows.Next() {
		var i ListInboxFeedRow
		if err := rows.Scan(
			&i.EntryType,
			&i.Kind,
			&i.SourceUserID,
			&i.SourceUsername,
			&i.RefRoomID,
			&i.RefConversationID,
			&i.UnreadCount,
			&i.LastMessageBody,
			&i.LastMessageSenderID,
			&i.RoomName,
			&i.PeerID,
			&i.PeerUsername,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetAllUnreadCount = `-- name: ResetAllUnreadCount :exec
UPDATE inbox_conversations
SET unread_count = 0
WHERE user_id = $1
`

func (q *Queries) ResetAllUnreadCount(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, resetAllUnreadCount, userID)
	return err
}

const resetDMUnreadCount = `-- name: ResetDMUnreadCount :exec
UPDATE inbox_conversations
SET unread_count = 0
WHERE ref_conversation_id = $1
AND user_id = $2
`

type ResetDMUnreadCountParams struct {
	ConversationID pgtype.Int8
	UserID         int64
}

func (q *Queries) ResetDMUnreadCount(ctx context.Context, arg ResetDMUnreadCountParams) error {
	_, err := q.db.Exec(ctx, resetDMUnreadCount, arg.ConversationID, arg.UserID)
	return err
}

const resetRoomUnreadCount = `-- name: ResetRoomUnreadCount :exec
UPDATE inbox_conversations
SET unread_count = 0
WHERE ref_room_id = $1
AND user_id = $2
`

type ResetRoomUnreadCountParams struct {
	RoomID pgtype.Int8
	UserID int64
}

func (q *Queries) ResetRoomUnreadCount(ctx context.Context, arg ResetRoomUnreadCountParams) error {
	_, err := q.db.Exec(ctx, resetRoomUnreadCount, arg.RoomID, arg.UserID)
	return err
}

const saveInboxRoomEvent = `-- name: SaveInboxRoomEvent :exec
INSERT INTO inbox_events (user_id, kind, room_id, source_user_id)
    SELECT rm.user_id, $1, $2, $3
    FROM room_members rm
    WHERE rm.room_id = $2
    AND rm.user_id != $3
`

type SaveInboxRoomEventParams struct {
	Kind         string
	RoomID       pgtype.Int8
	SourceUserID int64
}

func (q *Queries) SaveInboxRoomEvent(ctx context.Context, arg SaveInboxRoomEventParams) error {
	_, err := q.db.Exec(ctx, saveInboxRoomEvent, arg.Kind, arg.RoomID, arg.SourceUserID)
	return err
}

const updateInboxCursorOnDMMessage = `-- name: UpdateInboxCursorOnDMMessage :many
WITH updated AS (
    UPDATE inbox_conversations
    SET last_message_body      = $1,
        last_message_at        = NOW(),
        last_message_sender_id = $2,
        unread_count           = unread_count + 1
    WHERE user_id = $3
      AND ref_conversation_id = $4
    RETURNING id, user_id, ref_room_id, ref_conversation_id, last_read_message_id, created_at, last_message_body, last_message_at, last_message_sender_id, unread_count
)
SELECT
    'conversation'::text   AS entry_type,
    ''::text               AS kind,
    0::bigint              AS source_user_id,
    ''::text               AS source_username,
    ref_room_id,
    ref_conversation_id,
    unread_count::bigint,
    last_message_body,
    last_message_sender_id,
    r.name                 AS room_name,
    COALESCE(peer.id, 0)   AS peer_id,
    COALESCE(peer.username, '') AS peer_username,
    last_message_at     AS created_at,
    updated.user_id
FROM updated
LEFT JOIN rooms r ON r.id = ref_room_id
LEFT JOIN conversations c ON c.id = ref_conversation_id
LEFT JOIN users peer ON peer.id = CASE WHEN c.user_a = updated.user_id::bigint THEN c.user_b ELSE c.user_a END
`

type UpdateInboxCursorOnDMMessageParams struct {
	Body           pgtype.Text
	SenderID       pgtype.Int8
	RecipientID    int64
	ConversationID pgtype.Int8
}

type UpdateInboxCursorOnDMMessageRow struct {
	EntryType           string
	Kind                string
	SourceUserID        int64
	SourceUsername      string
	RefRoomID           pgtype.Int8
	RefConversationID   pgtype.Int8
	UnreadCount         int64
	LastMessageBody     pgtype.Text
	LastMessageSenderID pgtype.Int8
	RoomName            pgtype.Text
	PeerID              int64
	PeerUsername        string
	CreatedAt           pgtype.Timestamptz
	UserID              int64
}

// Filters by user_id with equality (instead of != sender_id) so the partial index
// inbox_conv_user_conv_uniq (user_id, ref_conversation_id) is used directly.
// Filtering with != on the leading column forces a full index scan.
func (q *Queries) UpdateInboxCursorOnDMMessage(ctx context.Context, arg UpdateInboxCursorOnDMMessageParams) ([]UpdateInboxCursorOnDMMessageRow, error) {
	rows, err := q.db.Query(ctx, updateInboxCursorOnDMMessage,
		arg.Body,
		arg.SenderID,
		arg.RecipientID,
		arg.ConversationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateInboxCursorOnDMMessageRow
	for rows.Next() {
		var i UpdateInboxCursorOnDMMessageRow
		if err := rows.Scan(
			&i.EntryType,
			&i.Kind,
			&i.SourceUserID,
			&i.SourceUsername,
			&i.RefRoomID,
			&i.RefConversationID,
			&i.UnreadCount,
			&i.LastMessageBody,
			&i.LastMessageSenderID,
			&i.RoomName,
			&i.PeerID,
			&i.PeerUsername,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInboxCursorOnRoomMessage = `-- name: UpdateInboxCursorOnRoomMessage :many
WITH updated AS (
    UPDATE inbox_conversations
    SET last_message_body      = $1,
        last_message_at        = NOW(),
        last_message_sender_id = $2,
        unread_count           = unread_count + 1
    WHERE ref_room_id = $3
      AND user_id != $2
    RETURNING id, user_id, ref_room_id, ref_conversation_id, last_read_message_id, created_at, last_message_body, last_message_at, last_message_sender_id, unread_count
)
SELECT
    'conversation'::text             AS entry_type,
    ''::text                         AS kind,
    0::bigint                        AS source_user_id,
    ''::text                         AS source_username,
    updated.ref_room_id,
    updated.ref_conversation_id,
    updated.unread_count::bigint    AS unread_count,
    updated.last_message_body,
    updated.last_message_sender_id,
    r.name                           AS room_name,
    COALESCE(peer.id, 0)             AS peer_id,
    COALESCE(peer.username, '')      AS peer_username,
    updated.last_message_at          AS created_at,
    updated.user_id
FROM updated
LEFT JOIN rooms r ON r.id = updated.ref_room_id
LEFT JOIN conversations c ON c.id = updated.ref_conversation_id
LEFT JOIN users peer ON peer.id = CASE
    WHEN c.user_a = updated.user_id THEN c.user_b
    ELSE c.user_a
END
`

type UpdateInboxCursorOnRoomMessageParams struct {
	Body     pgtype.Text
	SenderID pgtype.Int8
	RoomID   pgtype.Int8
}

type UpdateInboxCursorOnRoomMessageRow struct {
	EntryType           string
	Kind                string
	SourceUserID        int64
	SourceUsername      string
	RefRoomID           pgtype.Int8
	RefConversationID   pgtype.Int8
	UnreadCount         int64
	LastMessageBody     pgtype.Text
	LastMessageSenderID pgtype.Int8
	RoomName            pgtype.Text
	PeerID              int64
	PeerUsername        string
	CreatedAt           pgtype.Timestamptz
	UserID              int64
}

func (q *Queries) UpdateInboxCursorOnRoomMessage(ctx context.Context, arg UpdateInboxCursorOnRoomMessageParams) ([]UpdateInboxCursorOnRoomMessageRow, error) {
	rows, err := q.db.Query(ctx, updateInboxCursorOnRoomMessage, arg.Body, arg.SenderID, arg.RoomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateInboxCursorOnRoomMessageRow
	for rows.Next() {
		var i UpdateInboxCursorOnRoomMessageRow
		if err := rows.Scan(
			&i.EntryType,
			&i.Kind,
			&i.SourceUserID,
			&i.SourceUsername,
			&i.RefRoomID,
			&i.RefConversationID,
			&i.UnreadCount,
			&i.LastMessageBody,
			&i.LastMessageSenderID,
			&i.RoomName,
			&i.PeerID,
			&i.PeerUsername,
			&i.CreatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInboxConversationCursor = `-- name: UpsertInboxConversationCursor :exec
INSERT INTO inbox_conversations (user_id, ref_room_id, ref_conversation_id)
    VALUES ($1, $2, $3)
    ON CONFLICT DO NOTHING
`

type UpsertInboxConversationCursorParams struct {
	UserID            int64
	RefRoomID         pgtype.Int8
	RefConversationID pgtype.Int8
}

func (q *Queries) UpsertInboxConversationCursor(ctx context.Context, arg UpsertInboxConversationCursorParams) error {
	_, err := q.db.Exec(ctx, upsertInboxConversationCursor, arg.UserID, arg.RefRoomID, arg.RefConversationID)
	return err
}
