// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveRoomEvent = `-- name: SaveRoomEvent :exec
INSERT INTO inbox_events (user_id, kind, room_id, source_user_id)
    SELECT rm.user_id, $1, $2, $3
    FROM room_members rm
    WHERE rm.room_id = $2
    AND rm.user_id != $3
`

type SaveRoomEventParams struct {
	Kind         string
	RoomID       pgtype.Int8
	SourceUserID int64
}

func (q *Queries) SaveRoomEvent(ctx context.Context, arg SaveRoomEventParams) error {
	_, err := q.db.Exec(ctx, saveRoomEvent, arg.Kind, arg.RoomID, arg.SourceUserID)
	return err
}
