name: test

on:
  push:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod

      - run: go test -short ./...

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.4.0
        with:
          go-version-file: go.mod

      - name: run integration tests
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"
        run: go test ./cmd/server/internal/auth/... ./cmd/server/internal/room/...
